[package]
authors = ["alex <acdenissk69@gmail.com>", "Zeyla Hellyer <zey@zey.moe>"]
description = "A Rust library for the Discord API."
documentation = "https://docs.rs/serenity"
homepage = "https://github.com/zeyla/serenity"
keywords = ["discord", "api"]
license = "ISC"
name = "serenity"
readme = "README.md"
repository = "https://github.com/zeyla/serenity.git"
version = "0.6.0"

[dependencies]
bitflags = "^1.0"
future-utils = "~0.9"
futures = "~0.1"
log = "~0.4"
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"
tokio-core = "~0.1"
tokio-timer = "~0.1"
tokio-tls = "~0.1"
url = "^1.6"

[dependencies.base64]
optional = true
version = "~0.9"

[dependencies.byteorder]
optional = true
version = "^1.2"

[dependencies.chrono]
features = ["serde"]
version = "~0.4"

[dependencies.flate2]
optional = true
version = "^1.0"

[dependencies.hyper]
optional = true
version = "~0.11"

[dependencies.hyper-multipart-rfc7578]
optional = true
version = "0.1.0-alpha3"

[dependencies.hyper-tls]
optional = true
version = "~0.1"

[dependencies.native-tls]
optional = true
version = "~0.1"

[dependencies.opus]
optional = true
version = "0.2"

[dependencies.parking_lot]
optional = true
version = "~0.5"

[dependencies.rand]
optional = true
version = "^0.4"

[dependencies.sodiumoxide]
default-features = false
optional = true
version = "0.0.14"

[dependencies.tokio-tungstenite]
optional = true
version = "~0.4"

[dependencies.tungstenite]
optional = true
version = "~0.5"

[dev-dependencies.matches]
version = "0.1.6"

[features]
default = [
    "builder",
    "client",
    "gateway",
    "http",
    "utils",
]
builder = ["utils"]
client = ["gateway", "http"]
extras = []
framework = ["client", "utils"]
gateway = ["flate2", "http", "tokio-tungstenite", "tungstenite", "utils"]
http = ["builder", "hyper", "hyper-multipart-rfc7578", "hyper-tls", "native-tls", "utils"]
standard_framework = ["framework"]
utils = ["base64"]
voice = ["byteorder", "gateway", "opus", "parking_lot", "rand", "sodiumoxide"]

[package.metadata.docs.rs]
all-features = true
