[package]
name = "e15_voice_storage"
version = "0.1.0"
authors = ["my name <my@email.address>"]
edition = "2018"

[dependencies.serenity]
features = ["cache", "framework", "standard_framework", "voice", "http", "rustls_backend"]
path = "../../"

[dependencies.tokio]
version = "0.2"
features = ["macros"]

[dependencies]
env_logger = "0.7"